-- Creamos las tablas:
/*
create or replace TABLE E_COMMERCE.PRESENTATION.FACT_TABLE (
	ORDER_DATE DATE,
	TIME TIME(9),
	AGING NUMBER(38,1),
	CUSTOMER_ID NUMBER(38,0),
	DEVICE_TYPE VARCHAR(16777216),
	SALES NUMBER(38,1),
	QUANTITY NUMBER(38,1),
	DISCOUNT NUMBER(38,1),
	PROFIT NUMBER(38,1),
	SHIPPING_COST NUMBER(38,1),
	ORDER_PRIORITY VARCHAR(16777216),
	PAYMENT_METHOD VARCHAR(16777216),
	ORDER_ID NUMBER(38,0),
	PRODUCT_ID NUMBER(38,0),
    etl_last_updated_date TIMESTAMP
);*/
/*
create or replace TABLE E_COMMERCE.PRESENTATION.DIM_PRODUCT (
	PRODUCT_NAME VARCHAR(16777216),
	CATEGORY_ID NUMBER(38,0),
	PRODUCT_ID NUMBER(38,0),
    etl_last_updated_date TIMESTAMP
);*/
/*
create or replace TABLE E_COMMERCE.PRESENTATION.DIM_COSTUMER (
	CUSTOMER_ID NUMBER(38,0),
	CUSTOMER_LOGIN_TYPE VARCHAR(16777216),
	GENDER VARCHAR(16777216),
    etl_last_updated_date TIMESTAMP
);*/
/*
create or replace TABLE E_COMMERCE.PRESENTATION.DIM_CATEGORY (
	CATEGORY_NAME VARCHAR(16777216),
	CATEGORY_ID NUMBER(38,0),
    etl_last_updated_date TIMESTAMP
);*/
/*
CREATE OR REPLACE TABLE E_COMMERCE.PRESENTATION.archivos_procesados (
    nombre_archivo STRING PRIMARY KEY,
    fecha_proceso TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);*/

-- Consultas para ver las tablas:
-- SELECT * FROM E_COMMERCE.PRESENTATION.FACT_TABLE;
-- SELECT * FROM E_COMMERCE.PRESENTATION.DIM_COSTUMER;
-- SELECT * FROM E_COMMERCE.PRESENTATION.DIM_CATEGORY;
-- SELECT * FROM E_COMMERCE.PRESENTATION.DIM_PRODUCT;